import type { CardDefinition, CardId } from './cardDatabase'

const SIG_PRICE = 32

/** M30 — three signature mechanic cards per class (merged into CARD_DATABASE). */
export const SIGNATURE_CARD_ENTRIES: Partial<Record<CardId, CardDefinition>> = {
  guardian_brace: {
    id: 'guardian_brace',
    name: 'Brace',
    cost: 1,
    block: 6,
    description: 'Gain 6 block.',
    mechanicHint: '+2 Resolve.',
    shopPrice: SIG_PRICE,
  },
  guardian_shield_crush: {
    id: 'guardian_shield_crush',
    name: 'Shield Crush',
    cost: 2,
    damage: 5,
    description: 'Spend 3 Resolve: deal 8 damage. Otherwise deal 5.',
    mechanicHint: 'Costs 3 Resolve for full effect.',
    shopPrice: SIG_PRICE,
  },
  guardian_stand_firm: {
    id: 'guardian_stand_firm',
    name: 'Stand Firm',
    cost: 1,
    description: 'Gain block equal to your Resolve (min 3).',
    mechanicHint: 'Scales with Resolve.',
    shopPrice: SIG_PRICE,
  },
  berserker_enrage: {
    id: 'berserker_enrage',
    name: 'Enrage',
    cost: 0,
    description: 'Gain 3 Rage. Lose 2 HP.',
    mechanicHint: '+3 Rage.',
    shopPrice: SIG_PRICE,
  },
  berserker_blood_strike: {
    id: 'berserker_blood_strike',
    name: 'Blood Strike',
    cost: 2,
    damage: 4,
    description: 'Deal 4 damage plus your Rage.',
    mechanicHint: 'Bonus damage = current Rage.',
    shopPrice: SIG_PRICE,
  },
  berserker_reckless_charge: {
    id: 'berserker_reckless_charge',
    name: 'Reckless Charge',
    cost: 1,
    damage: 6,
    description: 'Deal 6 damage. Gain 2 Rage. Lose all block.',
    mechanicHint: '+2 Rage, removes block.',
    shopPrice: SIG_PRICE,
  },
  gunslinger_quick_shot: {
    id: 'gunslinger_quick_shot',
    name: 'Quick Shot',
    cost: 1,
    damage: 3,
    description: 'Deal 3 damage. Gain 2 Combo.',
    mechanicHint: '+2 Combo.',
    shopPrice: SIG_PRICE,
  },
  gunslinger_chain_fire: {
    id: 'gunslinger_chain_fire',
    name: 'Chain Fire',
    cost: 2,
    damage: 4,
    description: 'Deal 4 damage plus your Combo.',
    mechanicHint: 'Bonus damage = current Combo.',
    shopPrice: SIG_PRICE,
  },
  gunslinger_reload: {
    id: 'gunslinger_reload',
    name: 'Reload',
    cost: 1,
    description: 'Reset Combo to 0. Draw 2 cards.',
    mechanicHint: 'Sets Combo to 0, then draw.',
    shopPrice: SIG_PRICE,
  },
  necromancer_harvest: {
    id: 'necromancer_harvest',
    name: 'Harvest',
    cost: 1,
    description: 'Gain 3 Souls.',
    mechanicHint: '+3 Souls.',
    shopPrice: SIG_PRICE,
  },
  necromancer_bone_spear: {
    id: 'necromancer_bone_spear',
    name: 'Bone Spear',
    cost: 2,
    damage: 4,
    description: 'Spend 3 Souls: deal 9 damage. Otherwise deal 4.',
    mechanicHint: 'Costs 3 Souls for full effect.',
    shopPrice: SIG_PRICE,
  },
  necromancer_soul_guard: {
    id: 'necromancer_soul_guard',
    name: 'Soul Guard',
    cost: 1,
    description: 'Spend 2 Souls: gain 8 block and heal 2. Otherwise gain 4 block.',
    mechanicHint: 'Costs 2 Souls for block + heal.',
    shopPrice: SIG_PRICE,
  },
  vampire_bloodletting: {
    id: 'vampire_bloodletting',
    name: 'Bloodletting',
    cost: 0,
    description: 'Lose 3 HP. Draw 2 cards. Gain 1 Blood.',
    mechanicHint: 'Self-damage; +1 Blood.',
    shopPrice: SIG_PRICE,
  },
  vampire_crimson_bite: {
    id: 'vampire_crimson_bite',
    name: 'Crimson Bite',
    cost: 1,
    damage: 5,
    description: 'Deal 5 damage. Heal 2 if Blood is 4+.',
    mechanicHint: 'Heal 2 at 4+ Blood.',
    shopPrice: SIG_PRICE,
  },
  vampire_blood_shield: {
    id: 'vampire_blood_shield',
    name: 'Blood Shield',
    cost: 1,
    description: 'Lose 2 HP. Gain 10 block.',
    mechanicHint: 'Trades HP for block.',
    shopPrice: SIG_PRICE,
  },
  pirate_heist: {
    id: 'pirate_heist',
    name: 'Heist',
    cost: 1,
    damage: 4,
    description: 'Deal 4 damage. Gain 2 Booty.',
    mechanicHint: '+2 Booty.',
    shopPrice: SIG_PRICE,
  },
  pirate_cannon_volley: {
    id: 'pirate_cannon_volley',
    name: 'Cannon Volley',
    cost: 2,
    damage: 3,
    description: 'Deal 3 damage plus your Booty.',
    mechanicHint: 'Bonus damage = current Booty.',
    shopPrice: SIG_PRICE,
  },
  pirate_treasure_cache: {
    id: 'pirate_treasure_cache',
    name: 'Treasure Cache',
    cost: 1,
    block: 5,
    description: 'Gain 5 block. Gain 3 Booty.',
    mechanicHint: '+3 Booty.',
    shopPrice: SIG_PRICE,
  },
  merchant_tithe: {
    id: 'merchant_tithe',
    name: 'Tithe',
    cost: 1,
    block: 4,
    description: 'Gain 4 block. Gain 2 Coin.',
    mechanicHint: '+2 Coin.',
    shopPrice: SIG_PRICE,
  },
  merchant_invoice: {
    id: 'merchant_invoice',
    name: 'Invoice',
    cost: 2,
    damage: 4,
    description: 'Deal 4 damage plus half your Coin (rounded down).',
    mechanicHint: 'Bonus = floor(Coin ÷ 2).',
    shopPrice: SIG_PRICE,
  },
  merchant_hoard: {
    id: 'merchant_hoard',
    name: 'Hoard',
    cost: 0,
    description: 'Gain 3 Coin. Draw 1 card.',
    mechanicHint: '+3 Coin.',
    shopPrice: SIG_PRICE,
  },
  alchemist_distill: {
    id: 'alchemist_distill',
    name: 'Distill',
    cost: 1,
    description: 'Gain 2 Brew. Draw 1 card.',
    mechanicHint: '+2 Brew.',
    shopPrice: SIG_PRICE,
  },
  alchemist_acid_flask: {
    id: 'alchemist_acid_flask',
    name: 'Acid Flask',
    cost: 2,
    damage: 5,
    description: 'Deal 5 damage plus your Brew.',
    mechanicHint: 'Bonus damage = current Brew.',
    shopPrice: SIG_PRICE,
  },
  alchemist_elixir_surge: {
    id: 'alchemist_elixir_surge',
    name: 'Elixir Surge',
    cost: 1,
    description: 'Spend 3 Brew: heal 5. Otherwise heal 1.',
    mechanicHint: 'Costs 3 Brew for big heal.',
    shopPrice: SIG_PRICE,
  },
  timekeeper_tick: {
    id: 'timekeeper_tick',
    name: 'Tick',
    cost: 1,
    description: 'Gain 2 Time.',
    mechanicHint: '+2 Time.',
    shopPrice: SIG_PRICE,
  },
  timekeeper_chrono_bolt: {
    id: 'timekeeper_chrono_bolt',
    name: 'Chrono Bolt',
    cost: 2,
    damage: 4,
    description: 'Deal 4 damage plus your Time.',
    mechanicHint: 'Bonus damage = current Time.',
    shopPrice: SIG_PRICE,
  },
  timekeeper_rewind: {
    id: 'timekeeper_rewind',
    name: 'Rewind',
    cost: 1,
    description: 'If Time is 3+: heal 4 and gain 1 Time. Otherwise heal 1.',
    mechanicHint: 'Stronger at 3+ Time.',
    shopPrice: SIG_PRICE,
  },
  pyromancer_kindle: {
    id: 'pyromancer_kindle',
    name: 'Kindle',
    cost: 1,
    damage: 3,
    description: 'Deal 3 damage. Gain 2 Ember.',
    mechanicHint: '+2 Ember.',
    shopPrice: SIG_PRICE,
  },
  pyromancer_fireball: {
    id: 'pyromancer_fireball',
    name: 'Fireball',
    cost: 2,
    damage: 5,
    description: 'Deal 5 damage plus your Ember.',
    mechanicHint: 'Bonus damage = current Ember.',
    shopPrice: SIG_PRICE,
  },
  pyromancer_ignite_burst: {
    id: 'pyromancer_ignite_burst',
    name: 'Ignite Burst',
    cost: 1,
    damage: 4,
    description: 'Spend 4 Ember: deal 10 damage. Otherwise deal 4.',
    mechanicHint: 'Costs 4 Ember for full burst.',
    shopPrice: SIG_PRICE,
  },
  cryomancer_chill: {
    id: 'cryomancer_chill',
    name: 'Chill',
    cost: 1,
    block: 5,
    description: 'Gain 5 block. Gain 2 Frost.',
    mechanicHint: '+2 Frost.',
    shopPrice: SIG_PRICE,
  },
  cryomancer_ice_lance: {
    id: 'cryomancer_ice_lance',
    name: 'Ice Lance',
    cost: 2,
    damage: 4,
    description: 'Deal 4 damage plus your Frost.',
    mechanicHint: 'Bonus damage = current Frost.',
    shopPrice: SIG_PRICE,
  },
  cryomancer_glacier: {
    id: 'cryomancer_glacier',
    name: 'Glacier',
    cost: 1,
    description: 'Spend 3 Frost: gain 12 block. Otherwise gain 5 block.',
    mechanicHint: 'Costs 3 Frost for big block.',
    shopPrice: SIG_PRICE,
  },
  paladin_prayer: {
    id: 'paladin_prayer',
    name: 'Prayer',
    cost: 1,
    description: 'Gain 2 Faith. Heal 2 HP.',
    mechanicHint: '+2 Faith.',
    shopPrice: SIG_PRICE,
  },
  paladin_smite: {
    id: 'paladin_smite',
    name: 'Smite',
    cost: 2,
    damage: 5,
    description: 'Deal 5 damage plus your Faith.',
    mechanicHint: 'Bonus damage = current Faith.',
    shopPrice: SIG_PRICE,
  },
  paladin_bulwark: {
    id: 'paladin_bulwark',
    name: 'Bulwark',
    cost: 1,
    description: 'Spend 2 Faith: gain 9 block and heal 1. Otherwise gain 4 block.',
    mechanicHint: 'Costs 2 Faith for block + heal.',
    shopPrice: SIG_PRICE,
  },
  assassin_poised: {
    id: 'assassin_poised',
    name: 'Poised',
    cost: 1,
    description: 'Gain 2 Edge.',
    mechanicHint: '+2 Edge.',
    shopPrice: SIG_PRICE,
  },
  assassin_shadow_cut: {
    id: 'assassin_shadow_cut',
    name: 'Shadow Cut',
    cost: 2,
    damage: 6,
    description: 'Deal 6 damage plus your Edge.',
    mechanicHint: 'Bonus damage = current Edge.',
    shopPrice: SIG_PRICE,
  },
  assassin_ambush_prep: {
    id: 'assassin_ambush_prep',
    name: 'Ambush Prep',
    cost: 0,
    block: 3,
    description: 'Gain 3 block. Gain 3 Edge.',
    mechanicHint: '+3 Edge.',
    shopPrice: SIG_PRICE,
  },
  chef_chop: {
    id: 'chef_chop',
    name: 'Chop',
    cost: 1,
    damage: 5,
    description: 'Deal 5 damage. Gain 1 Prep.',
    mechanicHint: '+1 Prep.',
    shopPrice: SIG_PRICE,
  },
  chef_simmer: {
    id: 'chef_simmer',
    name: 'Simmer',
    cost: 1,
    block: 4,
    description: 'Gain 4 block. Gain 2 Prep.',
    mechanicHint: '+2 Prep.',
    shopPrice: SIG_PRICE,
  },
  chef_plated_feast: {
    id: 'chef_plated_feast',
    name: 'Plated Feast',
    cost: 2,
    description: 'Gain block equal to Prep × 2 + 4.',
    mechanicHint: 'Scales with Prep.',
    shopPrice: SIG_PRICE,
  },
  dragon_knight_hoard: {
    id: 'dragon_knight_hoard',
    name: 'Hoard',
    cost: 1,
    description: 'Gain 2 Scale.',
    mechanicHint: '+2 Scale.',
    shopPrice: SIG_PRICE,
  },
  dragon_knight_drake_fire: {
    id: 'dragon_knight_drake_fire',
    name: 'Drake Fire',
    cost: 2,
    damage: 5,
    description: 'Deal 5 damage plus your Scale.',
    mechanicHint: 'Bonus damage = current Scale.',
    shopPrice: SIG_PRICE,
  },
  dragon_knight_armor_plate: {
    id: 'dragon_knight_armor_plate',
    name: 'Armor Plate',
    cost: 1,
    description: 'Gain block equal to Scale + 3.',
    mechanicHint: 'Scales with Scale.',
    shopPrice: SIG_PRICE,
  },
  gambler_chip: {
    id: 'gambler_chip',
    name: 'Chip',
    cost: 1,
    damage: 3,
    description: 'Deal 3 damage. Gain 2 Luck.',
    mechanicHint: '+2 Luck.',
    shopPrice: SIG_PRICE,
  },
  gambler_jackpot_shot: {
    id: 'gambler_jackpot_shot',
    name: 'Jackpot Shot',
    cost: 2,
    damage: 4,
    description: 'Deal 4 damage plus Luck × 2.',
    mechanicHint: 'Bonus = Luck × 2.',
    shopPrice: SIG_PRICE,
  },
  gambler_all_in: {
    id: 'gambler_all_in',
    name: 'All In',
    cost: 0,
    damage: 4,
    description: 'Gain 3 Luck. Deal 4–8 damage at random.',
    mechanicHint: '+3 Luck; random damage.',
    shopPrice: SIG_PRICE,
  },
  bard_verse: {
    id: 'bard_verse',
    name: 'Verse',
    cost: 1,
    description: 'Gain 2 Verse. Draw 1 card.',
    mechanicHint: '+2 Verse.',
    shopPrice: SIG_PRICE,
  },
  bard_crescendo: {
    id: 'bard_crescendo',
    name: 'Crescendo',
    cost: 2,
    damage: 4,
    description: 'Deal 4 damage plus your Verse.',
    mechanicHint: 'Bonus damage = current Verse.',
    shopPrice: SIG_PRICE,
  },
  bard_harmony_shield: {
    id: 'bard_harmony_shield',
    name: 'Harmony Shield',
    cost: 1,
    description: 'Spend 3 Verse: gain 8 block and draw 1. Otherwise gain 4 block.',
    mechanicHint: 'Costs 3 Verse for block + draw.',
    shopPrice: SIG_PRICE,
  },
  engineer_wind_up: {
    id: 'engineer_wind_up',
    name: 'Wind Up',
    cost: 1,
    description: 'Gain 2 Charge.',
    mechanicHint: '+2 Charge.',
    shopPrice: SIG_PRICE,
  },
  engineer_pulse_blast: {
    id: 'engineer_pulse_blast',
    name: 'Pulse Blast',
    cost: 2,
    damage: 4,
    description: 'Deal 4 damage plus your Charge.',
    mechanicHint: 'Bonus damage = current Charge.',
    shopPrice: SIG_PRICE,
  },
  engineer_overcharge: {
    id: 'engineer_overcharge',
    name: 'Overcharge',
    cost: 1,
    description: 'Spend 3 Charge: gain 2 energy. Otherwise gain 1 Charge.',
    mechanicHint: 'Costs 3 Charge for energy.',
    shopPrice: SIG_PRICE,
  },
  monk_breath: {
    id: 'monk_breath',
    name: 'Breath',
    cost: 1,
    description: 'Gain 2 Focus.',
    mechanicHint: '+2 Focus.',
    shopPrice: SIG_PRICE,
  },
  monk_palm_burst: {
    id: 'monk_palm_burst',
    name: 'Palm Burst',
    cost: 2,
    damage: 5,
    description: 'Deal 5 damage plus your Focus.',
    mechanicHint: 'Bonus damage = current Focus.',
    shopPrice: SIG_PRICE,
  },
  monk_meditation: {
    id: 'monk_meditation',
    name: 'Meditation',
    cost: 0,
    block: 5,
    description: 'Gain 5 block. Gain 3 Focus.',
    mechanicHint: '+3 Focus.',
    shopPrice: SIG_PRICE,
  },
  warlord_rally: {
    id: 'warlord_rally',
    name: 'Rally',
    cost: 1,
    description: 'Gain 2 Momentum.',
    mechanicHint: '+2 Momentum.',
    shopPrice: SIG_PRICE,
  },
  warlord_charge: {
    id: 'warlord_charge',
    name: 'Charge',
    cost: 2,
    damage: 5,
    description: 'Deal 5 damage plus your Momentum.',
    mechanicHint: 'Bonus damage = current Momentum.',
    shopPrice: SIG_PRICE,
  },
  warlord_siege_wall: {
    id: 'warlord_siege_wall',
    name: 'Siege Wall',
    cost: 1,
    description: 'Gain block equal to Momentum + 4.',
    mechanicHint: 'Scales with Momentum.',
    shopPrice: SIG_PRICE,
  },
}

export const SIGNATURE_CARD_IDS = Object.keys(
  SIGNATURE_CARD_ENTRIES,
) as CardId[]
